---
- name: configure the dev env
  hosts: all
  become: true
  user: vagrant
  vars_files:
    - "vars/main.yml"

  roles:
    - common
    - hosting_tools
    - drupal
    - { role: geerlingguy.mailhog }
